(()=>{
'use strict';
let eleitorado=[],filiados=[],loadedE=false,loadedF=false;
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(n)||0));
const sum=(a,k)=>a.reduce((s,r)=>s+(Number(r[k])||0),0);
const group=(a,k,v)=>{const o={};a.forEach(r=>{const x=r[k]||'Não informado';o[x]=(o[x]||0)+(Number(r[v])||0)});return o};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function client(){try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch{return null}}
function opts(a,k){return [...new Set(a.map(r=>r[k]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'))}
function select(id,label,values){return `<select id="${id}"><option value="">${label}: Todos</option>${values.map(v=>`<option>${esc(v)}</option>`).join('')}</select>`}
function page(id,title,desc,kind){let root=document.getElementById(id);if(root)return root;root=document.createElement('section');root.id=id;root.className='tab-content';root.innerHTML=`<div class="analytics-page"><div class="analytics-head"><div><h2>${title}</h2><p>${desc}</p></div></div><div id="${kind}-body" class="analytics-loading">Carregando dados protegidos…</div></div>`;document.body.appendChild(root);return root}
function setTab(id,btn){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');if(id==='tab-eleitorado')loadEleitorado();if(id==='tab-filiacoes')loadFiliados()}
window.atlasAnalyticsTab=setTab;
function polish(){document.querySelectorAll('.brand-logo').forEach(i=>i.src='atlas_logo_.png');const h=document.querySelector('.brand-text h1');if(h)h.textContent='ATLAS ELEITORAL • ITAJAÍ'}
function injectNativeCss(){if(document.getElementById('native-analytics-css'))return;const s=document.createElement('style');s.id='native-analytics-css';s.textContent=`
.native-chart{width:100%;padding:8px 2px 4px}.native-bars{display:flex;flex-direction:column;gap:11px}.native-bar-row{display:grid;grid-template-columns:minmax(120px,210px) minmax(0,1fr) 78px;align-items:center;gap:12px;min-height:28px}.native-bar-row.clickable{cursor:pointer;border-radius:8px;padding:3px 5px;margin:-3px -5px}.native-bar-row.clickable:hover{background:#f8fafc}.native-bar-label{font-size:11px;font-weight:700;color:#475569;text-align:right;line-height:1.2;overflow-wrap:anywhere}.native-bar-track{height:20px;border-radius:7px;background:#f1f5f9;overflow:visible;position:relative}.native-bar-fill{height:100%;border-radius:7px;background:linear-gradient(90deg,#2563eb,#3b82f6);min-width:2px;transition:width .25s ease}.native-bar-row.active .native-bar-fill{background:#0f172a}.native-bar-value{font-size:11px;font-weight:800;color:#334155;text-align:left;white-space:nowrap}.native-donut-layout{display:grid;grid-template-columns:minmax(190px,300px) minmax(190px,1fr);gap:26px;align-items:center;min-height:270px}.native-donut{width:min(260px,80vw);aspect-ratio:1;border-radius:50%;position:relative;margin:auto}.native-donut::after{content:'';position:absolute;inset:25%;background:#fff;border-radius:50%}.native-donut-center{position:absolute;inset:0;display:grid;place-items:center;z-index:2;text-align:center;pointer-events:none}.native-donut-center strong{font-size:24px;color:#0f172a}.native-donut-center span{display:block;font-size:9px;color:#94a3b8;text-transform:uppercase;letter-spacing:.6px;margin-top:2px}.native-legend{display:flex;flex-direction:column;gap:9px}.native-legend-row{display:grid;grid-template-columns:12px minmax(0,1fr) auto;gap:8px;align-items:center;font-size:11px;color:#475569}.native-dot{width:10px;height:10px;border-radius:50%}.native-legend-row strong{color:#0f172a}.analytics-card .chart-wrap{height:auto!important;min-height:270px!important}.analytics-card.wide .chart-wrap{height:auto!important}.party-chart-wrap{height:auto!important;min-height:500px!important}
@media(max-width:700px){.native-bar-row{grid-template-columns:100px minmax(0,1fr) 58px;gap:8px}.native-bar-label,.native-bar-value{font-size:10px}.native-bar-track{height:18px}.native-donut-layout{grid-template-columns:1fr;gap:14px}.native-legend{padding:0 8px}.party-chart-wrap{min-height:0!important}.native-bars{gap:9px}}
`;document.head.appendChild(s)}
const palette=['#2563eb','#06b6d4','#8b5cf6','#f59e0b','#10b981','#ef4444','#ec4899','#14b8a6','#6366f1','#84cc16','#f97316','#0ea5e9'];
function barHtml(obj,{sort='desc',selected='',clickClass=''}={}){let entries=Object.entries(obj);if(sort==='age'){const first=x=>{const m=String(x).match(/\d+/);return m?+m[0]:999};entries.sort((a,b)=>first(a[0])-first(b[0]))}else if(sort==='alpha')entries.sort((a,b)=>String(a[0]).localeCompare(String(b[0]),'pt-BR'));else entries.sort((a,b)=>b[1]-a[1]);const max=Math.max(...entries.map(x=>x[1]),1);return `<div class="native-chart native-bars">${entries.map(([label,value])=>`<div class="native-bar-row ${clickClass?'clickable':''} ${selected===label?'active':''}" ${clickClass?`data-${clickClass}="${esc(label)}"`:''}><div class="native-bar-label">${esc(label)}</div><div class="native-bar-track"><div class="native-bar-fill" style="width:${Math.max(0,100*value/max).toFixed(2)}%"></div></div><div class="native-bar-value">${fmt(value)}</div></div>`).join('')}</div>`}
function donutHtml(obj){const entries=Object.entries(obj).sort((a,b)=>b[1]-a[1]);const total=entries.reduce((s,x)=>s+x[1],0);let acc=0;const seg=[];entries.forEach(([_,v],i)=>{const a=total?100*acc/total:0;acc+=v;const b=total?100*acc/total:0;seg.push(`${palette[i%palette.length]} ${a}% ${b}%`)});return `<div class="native-donut-layout"><div class="native-donut" style="background:conic-gradient(${seg.join(',')||'#e2e8f0 0 100%'})"><div class="native-donut-center"><div><strong>${fmt(total)}</strong><span>Total</span></div></div></div><div class="native-legend">${entries.map(([l,v],i)=>`<div class="native-legend-row"><i class="native-dot" style="background:${palette[i%palette.length]}"></i><span>${esc(l)}</span><strong>${fmt(v)}</strong></div>`).join('')}</div></div>`}
async function loadEleitorado(){if(loadedE)return renderE();const c=client();if(!c)return err('eleitorado-body','Sessão Supabase indisponível.');const {data,error}=await c.from('eleitorado_2026').select('*').limit(20000);if(error||!data?.length)return err('eleitorado-body',error?.message||'A base do eleitorado não está disponível.');eleitorado=data;loadedE=true;renderE()}
function renderE(){const body=document.getElementById('eleitorado-body');if(!body)return;body.className='';body.innerHTML=`<div class="analytics-filters">${select('ef-genero','Gênero',opts(eleitorado,'genero'))}${select('ef-faixa','Faixa etária',opts(eleitorado,'faixa_etaria'))}${select('ef-instrucao','Escolaridade',opts(eleitorado,'grau_instrucao'))}</div><div class="analytics-kpis"><div class="analytics-kpi"><span>Eleitorado</span><strong id="ek-total">—</strong><small>TRE-SC • 2026</small></div><div class="analytics-kpi"><span>Biometria</span><strong id="ek-bio">—</strong><small id="ek-biop">—</small></div><div class="analytics-kpi"><span>Voto obrigatório</span><strong id="ek-obr">—</strong><small>eleitores</small></div><div class="analytics-kpi"><span>Com deficiência</span><strong id="ek-def">—</strong><small>cadastro eleitoral</small></div></div><div class="analytics-grid"><div class="analytics-card wide"><h3>Eleitorado por faixa etária</h3><p>Distribuição do eleitorado cadastrado por grupos de idade.</p><div id="ec-faixa" class="chart-wrap"></div></div><div class="analytics-card"><h3>Distribuição por gênero</h3><p>Composição do eleitorado.</p><div id="ec-genero" class="chart-wrap"></div></div><div class="analytics-card"><h3>Grau de instrução</h3><p>Escolaridade declarada no cadastro eleitoral.</p><div id="ec-inst" class="chart-wrap"></div></div><div class="analytics-card"><h3>Cor / raça</h3><p>Distribuição segundo informação cadastral.</p><div id="ec-raca" class="chart-wrap"></div></div><div class="analytics-card"><h3>Estado civil</h3><p>Perfil cadastral do eleitorado.</p><div id="ec-civil" class="chart-wrap"></div></div></div>`;['ef-genero','ef-faixa','ef-instrucao'].forEach(id=>document.getElementById(id).onchange=updateE);updateE()}
function updateE(){const g=document.getElementById('ef-genero')?.value||'',f=document.getElementById('ef-faixa')?.value||'',i=document.getElementById('ef-instrucao')?.value||'';let ageBase=eleitorado;if(g)ageBase=ageBase.filter(r=>r.genero===g);if(i)ageBase=ageBase.filter(r=>r.grau_instrucao===i);let a=ageBase;if(f)a=a.filter(r=>r.faixa_etaria===f);const t=sum(a,'qtd_eleitores'),b=sum(a,'qtd_biometria');document.getElementById('ek-total').textContent=fmt(t);document.getElementById('ek-bio').textContent=fmt(b);document.getElementById('ek-biop').textContent=t?`${(100*b/t).toFixed(1).replace('.',',')}% do eleitorado`:'—';document.getElementById('ek-obr').textContent=fmt(sum(a,'qtd_voto_obrigatorio'));document.getElementById('ek-def').textContent=fmt(sum(a,'qtd_deficiencia'));document.getElementById('ec-faixa').innerHTML=barHtml(group(ageBase,'faixa_etaria','qtd_eleitores'),{sort:'age',selected:f,clickClass:'faixa'});document.querySelectorAll('[data-faixa]').forEach(el=>el.onclick=()=>{const sel=document.getElementById('ef-faixa');const v=el.dataset.faixa;sel.value=sel.value===v?'':v;updateE()});document.getElementById('ec-genero').innerHTML=donutHtml(group(a,'genero','qtd_eleitores'));document.getElementById('ec-inst').innerHTML=barHtml(group(a,'grau_instrucao','qtd_eleitores'));document.getElementById('ec-raca').innerHTML=donutHtml(group(a,'cor_raca','qtd_eleitores'));document.getElementById('ec-civil').innerHTML=barHtml(group(a,'estado_civil','qtd_eleitores'))}
async function loadFiliados(){if(loadedF)return renderF();const c=client();if(!c)return err('filiacoes-body','Sessão Supabase indisponível.');const {data,error}=await c.from('filiado_eleicao').select('*').limit(20000);if(error||!data?.length)return err('filiacoes-body',error?.message||'Não foi possível carregar a base.');filiados=data;loadedF=true;renderF()}
function renderF(){const body=document.getElementById('filiacoes-body');if(!body)return;body.className='';body.innerHTML=`<div class="analytics-filters">${select('ff-partido','Partido',opts(filiados,'partido'))}${select('ff-genero','Gênero',opts(filiados,'genero'))}${select('ff-faixa','Faixa etária',opts(filiados,'faixa_etaria'))}<button type="button" class="analytics-clear" id="ff-limpar">Limpar filtros</button></div><div class="analytics-kpis"><div class="analytics-kpi"><span>Filiados</span><strong id="fk-total">—</strong><small>base eleitoral 2024</small></div><div class="analytics-kpi"><span>Partidos</span><strong id="fk-partidos">—</strong><small>com filiados registrados</small></div><div class="analytics-kpi"><span>Mais de 10 anos</span><strong id="fk-antigos">—</strong><small>tempo de filiação</small></div><div class="analytics-kpi"><span>Com deficiência</span><strong id="fk-def">—</strong><small>filiados</small></div></div><div class="analytics-grid"><div class="analytics-card wide party-card"><div class="analytics-card-head"><div><h3>Filiados por partido</h3><p>Quantidade de filiados registrada por legenda. Clique ou toque em uma barra para filtrar os demais indicadores.</p></div><span id="ff-selecao" class="analytics-selection"></span></div><div id="fc-partido" class="chart-wrap party-chart-wrap"></div></div><div class="analytics-card"><h3>Faixa etária</h3><p>Distribuição etária dos filiados.</p><div id="fc-faixa" class="chart-wrap"></div></div><div class="analytics-card"><h3>Gênero</h3><p>Composição dos filiados.</p><div id="fc-genero" class="chart-wrap"></div></div><div class="analytics-card"><h3>Tempo de filiação</h3><p>Tempo de vínculo partidário informado.</p><div id="fc-tempo" class="chart-wrap"></div></div><div class="analytics-card"><h3>Escolaridade</h3><p>Grau de escolaridade dos filiados.</p><div id="fc-inst" class="chart-wrap"></div></div></div>`;['ff-partido','ff-genero','ff-faixa'].forEach(id=>document.getElementById(id).onchange=updateF);document.getElementById('ff-limpar').onclick=()=>{['ff-partido','ff-genero','ff-faixa'].forEach(id=>document.getElementById(id).value='');updateF()};updateF()}
function updateF(){const p=document.getElementById('ff-partido')?.value||'',g=document.getElementById('ff-genero')?.value||'',f=document.getElementById('ff-faixa')?.value||'';let base=filiados;if(g)base=base.filter(r=>r.genero===g);if(f)base=base.filter(r=>r.faixa_etaria===f);let a=base;if(p)a=a.filter(r=>r.partido===p);document.getElementById('fk-total').textContent=fmt(sum(a,'quantitativo_filiados'));document.getElementById('fk-partidos').textContent=fmt(new Set(a.map(r=>r.partido).filter(Boolean)).size);document.getElementById('fk-antigos').textContent=fmt(a.filter(r=>/mais de 10/i.test(r.tempo_filiacao||'')).reduce((s,r)=>s+(+r.quantitativo_filiados||0),0));document.getElementById('fk-def').textContent=fmt(sum(a,'quantitativo_deficiencia'));const tag=document.getElementById('ff-selecao');if(tag){tag.textContent=p?`Filtro ativo: ${p}`:'';tag.style.display=p?'inline-flex':'none'}document.getElementById('fc-partido').innerHTML=barHtml(group(base,'partido','quantitativo_filiados'),{selected:p,clickClass:'partido'});document.querySelectorAll('[data-partido]').forEach(el=>el.onclick=()=>{const sel=document.getElementById('ff-partido');const v=el.dataset.partido;sel.value=sel.value===v?'':v;updateF()});document.getElementById('fc-faixa').innerHTML=barHtml(group(a,'faixa_etaria','quantitativo_filiados'),{sort:'age'});document.getElementById('fc-genero').innerHTML=donutHtml(group(a,'genero','quantitativo_filiados'));document.getElementById('fc-tempo').innerHTML=donutHtml(group(a,'tempo_filiacao','quantitativo_filiados'));document.getElementById('fc-inst').innerHTML=barHtml(group(a,'grau_escolaridade','quantitativo_filiados'))}
function err(id,msg){const e=document.getElementById(id);if(e)e.innerHTML=`<div class="analytics-error">${esc(msg)}</div>`}
function init(){injectNativeCss();polish();page('tab-eleitorado','Perfil do Eleitorado','Indicadores oficiais do cadastro eleitoral de Itajaí para análise da composição demográfica e das características do eleitorado.','eleitorado');page('tab-filiacoes','Filiação Partidária','Panorama quantitativo das filiações partidárias em Itajaí, com leitura por legenda e características demográficas dos filiados.','filiacoes')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();