(()=>{
const charts={};let eleitorado=[],filiados=[],loadedE=false,loadedF=false;
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(n)||0));
const sum=(a,k)=>a.reduce((s,r)=>s+(Number(r[k])||0),0);
const group=(a,k,v)=>{const o={};a.forEach(r=>{const x=r[k]||'Não informado';o[x]=(o[x]||0)+(Number(r[v])||0)});return o};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function client(){try{return typeof supabaseClient!=='undefined'?supabaseClient:null}catch{return null}}
function ensureChart(){return new Promise((ok,fail)=>{if(window.Chart)return ok();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js';s.onload=ok;s.onerror=fail;document.head.appendChild(s)})}
function destroy(id){if(charts[id]){charts[id].destroy();delete charts[id]}}
function chart(id,obj,type='bar',horizontal=false){destroy(id);const el=document.getElementById(id);if(!el)return;const entries=Object.entries(obj).sort((a,b)=>b[1]-a[1]);charts[id]=new Chart(el,{type,data:{labels:entries.map(x=>x[0]),datasets:[{data:entries.map(x=>x[1]),borderWidth:0,borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:horizontal?'y':'x',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmt(c.raw)}}},scales:{x:{grid:{display:false},ticks:{font:{size:10}}},y:{grid:{color:'#f1f5f9'},ticks:{font:{size:10}}}}}})}
function donut(id,obj){destroy(id);const el=document.getElementById(id);if(!el)return;charts[id]=new Chart(el,{type:'doughnut',data:{labels:Object.keys(obj),datasets:[{data:Object.values(obj),borderWidth:2,borderColor:'#fff'}]},options:{responsive:true,maintainAspectRatio:false,cutout:'66%',plugins:{legend:{position:'bottom',labels:{boxWidth:10,font:{size:10}}},tooltip:{callbacks:{label:c=>`${c.label}: ${fmt(c.raw)}`}}}}})}
function opts(a,k){return [...new Set(a.map(r=>r[k]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'))}
function select(id,label,values){return `<select id="${id}"><option value="">${label}: Todos</option>${values.map(v=>`<option>${esc(v)}</option>`).join('')}</select>`}
function page(id,title,desc,kind){let root=document.getElementById(id);if(root)return root;root=document.createElement('section');root.id=id;root.className='tab-content';root.innerHTML=`<div class="analytics-page"><div class="analytics-head"><div><h2>${title}</h2><p>${desc}</p></div></div><div id="${kind}-body" class="analytics-loading">Carregando dados protegidos…</div></div>`;document.body.appendChild(root);return root}
function setTab(id,btn){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));const el=document.getElementById(id);if(el)el.classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');if(id==='tab-eleitorado')loadEleitorado();if(id==='tab-filiacoes')loadFiliados();}
window.atlasAnalyticsTab=setTab;
function buildNav(){ /* navegação declarada diretamente no index.html */ }
function polish(){document.querySelectorAll('.brand-logo').forEach(i=>i.src='atlas_logo_.png');const h=document.querySelector('.brand-text h1');if(h)h.textContent='ATLAS ELEITORAL • ITAJAÍ';const s=document.querySelector('.brand-text span');if(s)s.textContent='Inteligência Geográfica';const eye=document.querySelector('.hero-eyebrow');if(eye)eye.textContent='ATLAS ELEITORAL • ITAJAÍ';const p=document.querySelector('.hero p');if(p)p.textContent='Plataforma de inteligência geográfica para leitura integrada do território eleitoral de Itajaí, reunindo indicadores oficiais e análises espaciais que apoiam a compreensão da distribuição do eleitorado, dos locais de votação e da população em idade eleitoral no município.'}
async function loadEleitorado(){if(loadedE)return renderE();const c=client();if(!c)return err('eleitorado-body','Sessão Supabase indisponível.');let {data,error}=await c.from('eleitorado_2026').select('*').limit(20000);if(error)return err('eleitorado-body',error.message);if(!data?.length){const {data:u}=await c.from('usuarios_autorizados').select('perfil').maybeSingle();if(u?.perfil==='admin'){const r=await c.functions.invoke('import-eleitorado-2026');if(!r.error){({data,error}=await c.from('eleitorado_2026').select('*').limit(20000));}}}if(error||!data?.length)return err('eleitorado-body','A base do eleitorado ainda está sendo preparada. Atualize a página em instantes.');eleitorado=data;loadedE=true;renderE()}
function renderE(){const body=document.getElementById('eleitorado-body');if(!body)return;body.className='';body.innerHTML=`<div class="analytics-filters">${select('ef-genero','Gênero',opts(eleitorado,'genero'))}${select('ef-faixa','Faixa etária',opts(eleitorado,'faixa_etaria'))}${select('ef-instrucao','Escolaridade',opts(eleitorado,'grau_instrucao'))}</div><div class="analytics-kpis"><div class="analytics-kpi"><span>Eleitorado</span><strong id="ek-total">—</strong><small>TRE-SC • 2026</small></div><div class="analytics-kpi"><span>Biometria</span><strong id="ek-bio">—</strong><small id="ek-biop">—</small></div><div class="analytics-kpi"><span>Voto obrigatório</span><strong id="ek-obr">—</strong><small>eleitores</small></div><div class="analytics-kpi"><span>Com deficiência</span><strong id="ek-def">—</strong><small>cadastro eleitoral</small></div></div><div class="analytics-grid"><div class="analytics-card wide"><h3>Eleitorado por faixa etária</h3><p>Distribuição do eleitorado cadastrado por grupos de idade.</p><div class="chart-wrap"><canvas id="ec-faixa"></canvas></div></div><div class="analytics-card"><h3>Distribuição por gênero</h3><p>Composição do eleitorado.</p><div class="chart-wrap"><canvas id="ec-genero"></canvas></div></div><div class="analytics-card"><h3>Grau de instrução</h3><p>Escolaridade declarada no cadastro eleitoral.</p><div class="chart-wrap"><canvas id="ec-inst"></canvas></div></div><div class="analytics-card"><h3>Cor / raça</h3><p>Distribuição segundo informação cadastral.</p><div class="chart-wrap"><canvas id="ec-raca"></canvas></div></div><div class="analytics-card"><h3>Estado civil</h3><p>Perfil cadastral do eleitorado.</p><div class="chart-wrap"><canvas id="ec-civil"></canvas></div></div></div>`;['ef-genero','ef-faixa','ef-instrucao'].forEach(id=>document.getElementById(id).onchange=updateE);ensureChart().then(updateE)}
function updateE(){let a=eleitorado;const g=document.getElementById('ef-genero')?.value,f=document.getElementById('ef-faixa')?.value,i=document.getElementById('ef-instrucao')?.value;if(g)a=a.filter(r=>r.genero===g);if(f)a=a.filter(r=>r.faixa_etaria===f);if(i)a=a.filter(r=>r.grau_instrucao===i);const t=sum(a,'qtd_eleitores'),b=sum(a,'qtd_biometria');document.getElementById('ek-total').textContent=fmt(t);document.getElementById('ek-bio').textContent=fmt(b);document.getElementById('ek-biop').textContent=t?`${(100*b/t).toFixed(1).replace('.',',')}% do eleitorado`:'—';document.getElementById('ek-obr').textContent=fmt(sum(a,'qtd_voto_obrigatorio'));document.getElementById('ek-def').textContent=fmt(sum(a,'qtd_deficiencia'));chart('ec-faixa',group(a,'faixa_etaria','qtd_eleitores'));donut('ec-genero',group(a,'genero','qtd_eleitores'));chart('ec-inst',group(a,'grau_instrucao','qtd_eleitores'),'bar',true);donut('ec-raca',group(a,'cor_raca','qtd_eleitores'));chart('ec-civil',group(a,'estado_civil','qtd_eleitores'),'bar',true)}
async function loadFiliados(){if(loadedF)return renderF();const c=client();if(!c)return err('filiacoes-body','Sessão Supabase indisponível.');const {data,error}=await c.from('filiado_eleicao').select('*').limit(20000);if(error||!data)return err('filiacoes-body',error?.message||'Não foi possível carregar a base.');filiados=data;loadedF=true;renderF()}
function renderF(){const body=document.getElementById('filiacoes-body');if(!body)return;body.className='';body.innerHTML=`<div class="analytics-filters">${select('ff-partido','Partido',opts(filiados,'partido'))}${select('ff-genero','Gênero',opts(filiados,'genero'))}${select('ff-faixa','Faixa etária',opts(filiados,'faixa_etaria'))}</div><div class="analytics-kpis"><div class="analytics-kpi"><span>Filiados</span><strong id="fk-total">—</strong><small>base eleitoral 2024</small></div><div class="analytics-kpi"><span>Partidos</span><strong id="fk-partidos">—</strong><small>com filiados registrados</small></div><div class="analytics-kpi"><span>Mais de 10 anos</span><strong id="fk-antigos">—</strong><small>tempo de filiação</small></div><div class="analytics-kpi"><span>Com deficiência</span><strong id="fk-def">—</strong><small>filiados</small></div></div><div class="analytics-grid"><div class="analytics-card wide"><h3>Filiados por partido</h3><p>Quantidade de filiados registrada por legenda.</p><div class="chart-wrap"><canvas id="fc-partido"></canvas></div></div><div class="analytics-card"><h3>Faixa etária</h3><p>Distribuição etária dos filiados.</p><div class="chart-wrap"><canvas id="fc-faixa"></canvas></div></div><div class="analytics-card"><h3>Gênero</h3><p>Composição dos filiados.</p><div class="chart-wrap"><canvas id="fc-genero"></canvas></div></div><div class="analytics-card"><h3>Tempo de filiação</h3><p>Tempo de vínculo partidário informado.</p><div class="chart-wrap"><canvas id="fc-tempo"></canvas></div></div><div class="analytics-card"><h3>Escolaridade</h3><p>Grau de escolaridade dos filiados.</p><div class="chart-wrap"><canvas id="fc-inst"></canvas></div></div></div>`;['ff-partido','ff-genero','ff-faixa'].forEach(id=>document.getElementById(id).onchange=updateF);ensureChart().then(updateF)}
function updateF(){let a=filiados;const p=document.getElementById('ff-partido')?.value,g=document.getElementById('ff-genero')?.value,f=document.getElementById('ff-faixa')?.value;if(p)a=a.filter(r=>r.partido===p);if(g)a=a.filter(r=>r.genero===g);if(f)a=a.filter(r=>r.faixa_etaria===f);document.getElementById('fk-total').textContent=fmt(sum(a,'quantitativo_filiados'));document.getElementById('fk-partidos').textContent=fmt(new Set(a.map(r=>r.partido).filter(Boolean)).size);document.getElementById('fk-antigos').textContent=fmt(a.filter(r=>/mais de 10/i.test(r.tempo_filiacao||'')).reduce((s,r)=>s+(+r.quantitativo_filiados||0),0));document.getElementById('fk-def').textContent=fmt(sum(a,'quantitativo_deficiencia'));chart('fc-partido',group(a,'partido','quantitativo_filiados'),'bar',true);chart('fc-faixa',group(a,'faixa_etaria','quantitativo_filiados'));donut('fc-genero',group(a,'genero','quantitativo_filiados'));donut('fc-tempo',group(a,'tempo_filiacao','quantitativo_filiados'));chart('fc-inst',group(a,'grau_escolaridade','quantitativo_filiados'),'bar',true)}
function err(id,msg){const e=document.getElementById(id);if(e)e.innerHTML=`<div class="analytics-error">${esc(msg)}</div>`}
document.addEventListener('DOMContentLoaded',()=>{polish();buildNav();page('tab-eleitorado','Perfil do Eleitorado','Indicadores oficiais do cadastro eleitoral de Itajaí para análise da composição demográfica e das características do eleitorado.','eleitorado');page('tab-filiacoes','Filiação Partidária','Panorama quantitativo das filiações partidárias em Itajaí, com leitura por legenda e características demográficas dos filiados.','filiacoes')});
})();