(()=>{
'use strict';
const FILE20='cand_mais_votado-municipio_vereador_2020_sc_itajai.csv';
const FILE24='cand_mais_votado-municipio_vereador_2024_sc_itajai.csv';
let d20=null,d24=null;const charts={};
const fmt=n=>new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const pct=n=>`${fmt(n)}%`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toUpperCase();
const num=v=>Number(String(v??0).replace(/\./g,'').replace(',','.'))||0;
function parseCSV(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===';'&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))out.push(row);row=[]}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}if(!out.length)return[];const h=out.shift().map(x=>String(x).replace(/^\uFEFF/,'').trim());return out.map(r=>Object.fromEntries(h.map((k,i)=>[k,String(r[i]??'').trim()]))) }
const votes=r=>num(r.qt_votos_nom_validos), party=r=>r.sg_partido||'SEM PARTIDO', name=r=>r.nm_candidato||'NÃO INFORMADO';
const elected=r=>/^Eleito/i.test(String(r.ds_sit_tot_turno||'').trim());
function css(){if(document.getElementById('evo-css'))return;const l=document.createElement('link');l.id='evo-css';l.rel='stylesheet';l.href='evolution.css?v=1';document.head.appendChild(l)}
function icon(k){const p={votes:'<path d="M4 19h16M6 16h12M8 13h8M10 10h4M12 3v4"/>',party:'<path d="M3 21h18M5 21V9l7-5 7 5v12M9 21v-7h6v7"/>',up:'<path d="m4 16 6-6 4 4 6-7"/><path d="M15 7h5v5"/>',renew:'<path d="M20 7h-5V2M4 17h5v5"/><path d="M5.5 9a7 7 0 0 1 11.7-2.6L20 7M4 17l2.8.6A7 7 0 0 0 18.5 15"/>'};return `<svg viewBox="0 0 24 24">${p[k]}</svg>`}
function kpi(label,val,sub,k){return `<div class="evo-kpi"><div class="icon">${icon(k)}</div><span>${label}</span><strong>${val}</strong><small>${sub}</small></div>`}
function ensureNav(){const nav=document.querySelector('header nav');if(!nav||document.getElementById('nav-evolution'))return;const b=document.createElement('button');b.id='nav-evolution';b.className='nav-btn analytics-nav';b.textContent='Evolução 2020–2024';b.onclick=()=>show(b);nav.appendChild(b)}
function ensurePage(){let s=document.getElementById('tab-evolution');if(s)return s;s=document.createElement('section');s.id='tab-evolution';s.className='tab-content';s.innerHTML='<div class="evo-page"><div class="evo-head"><div><h2>Evolução Eleitoral 2020–2024</h2><p>Comparação descritiva dos resultados para vereador em Itajaí, com evolução de votos por partido, desempenho de candidaturas recorrentes e renovação entre os eleitos.</p></div></div><div id="evo-body">Carregando resultados de 2020 e 2024…</div></div>';document.body.appendChild(s);return s}
function show(btn){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));ensurePage().classList.add('active');btn.classList.add('active');load()}
async function load(){if(d20&&d24)return render();try{const [a,b]=await Promise.all([fetch(`${FILE20}?v=1`,{cache:'no-store'}),fetch(`${FILE24}?v=1`,{cache:'no-store'})]);if(!a.ok||!b.ok)throw new Error(`CSV ${a.status}/${b.status}`);d20=parseCSV(await a.text());d24=parseCSV(await b.text());render()}catch(e){console.error('Evolução eleitoral',e);document.getElementById('evo-body').innerHTML='<div class="evo-card">Não foi possível carregar os resultados eleitorais.</div>'}}
function partyTotals(rows){const m={};rows.forEach(r=>m[party(r)]=(m[party(r)]||0)+votes(r));return m}
function repeated(){const m20=new Map(d20.map(r=>[norm(name(r)),r]));return d24.map(r=>{const old=m20.get(norm(name(r)));return old?{nome:name(r),p20:party(old),p24:party(r),v20:votes(old),v24:votes(r),delta:votes(r)-votes(old),pct:votes(old)?100*(votes(r)-votes(old))/votes(old):null}:null}).filter(Boolean)}
function electedRows(rows){return rows.filter(elected)}
function destroy(id){if(charts[id]){charts[id].destroy();delete charts[id]}}
function opts(){return{responsive:true,maintainAspectRatio:false,animation:{duration:450},plugins:{legend:{labels:{usePointStyle:true,pointStyle:'circle',boxWidth:9,padding:18,font:{size:11}}},tooltip:{backgroundColor:'#0f172a',padding:11,callbacks:{label:c=>` ${c.dataset.label}: ${fmt(c.raw)}`}}}}}
function render(){const p20=partyTotals(d20),p24=partyTotals(d24);const total20=Object.values(p20).reduce((a,b)=>a+b,0),total24=Object.values(p24).reduce((a,b)=>a+b,0);const rep=repeated(),el20=electedRows(d20),el24=electedRows(d24);const set20=new Set(el20.map(r=>norm(name(r))));const reeleitos=el24.filter(r=>set20.has(norm(name(r)))).length,novos=el24.length-reeleitos;const body=document.getElementById('evo-body');body.innerHTML=`<div class="evo-kpis">${kpi('Votos nominais 2020',fmt(total20),'vereador • Itajaí','votes')}${kpi('Votos nominais 2024',fmt(total24),'vereador • Itajaí','votes')}${kpi('Variação total',`${total20?pct(100*(total24-total20)/total20):'—'}`,`${total24>=total20?'+':''}${fmt(total24-total20)} votos`,'up')}${kpi('Renovação entre eleitos',el24.length?pct(100*novos/el24.length):'0,00%',`${fmt(novos)} novos de ${fmt(el24.length)} eleitos`,'renew')}</div><div class="evo-grid"><div class="evo-card wide"><h3>Força dos partidos: 2020 x 2024</h3><p>Comparação dos 10 partidos com maior votação nominal em 2024. A leitura utiliza a sigla registrada em cada eleição.</p><div class="evo-chart tall"><canvas id="evo-party"></canvas></div><div id="evo-party-table"></div></div><div class="evo-card wide"><h3>Candidatos que concorreram nos dois anos</h3><p>Trajetória dos 15 candidatos com maior ganho absoluto de votos entre 2020 e 2024. O partido exibido à direita é o registrado em 2024.</p><div id="evo-slope" class="evo-chart slope"></div></div><div class="evo-card wide"><h3>Maiores aumentos e maiores quedas</h3><p>Comparação individual somente entre nomes presentes nas duas eleições.</p><div id="evo-gain-loss" class="evo-tables"></div></div><div class="evo-card wide"><h3>Renovação e destino dos votos</h3><p>Reeleição/renovação entre os eleitos de 2024 e proporção de votos nominais destinados a candidatos eleitos e não eleitos em cada ano.</p><div class="evo-renew"><div><div class="evo-chart"><canvas id="evo-renew"></canvas></div></div><div><div class="evo-chart"><canvas id="evo-status"></canvas></div></div></div><div class="evo-note">Critério de eleito: registros cuja situação começa por “Eleito”, incluindo classificações como “Eleito por QP” e “Eleito por média”. A comparação de candidatos usa o nome normalizado para localizar quem aparece nos dois arquivos.</div></div></div>`;drawParty(p20,p24);drawSlope(rep);drawTables(rep);drawRenew(el20,el24,reeleitos,novos);drawStatus()}
function drawParty(p20,p24){destroy('party');const labels=Object.keys(p24).sort((a,b)=>p24[b]-p24[a]).slice(0,10);const el=document.getElementById('evo-party');charts.party=new Chart(el,{type:'bar',data:{labels,datasets:[{label:'2020',data:labels.map(k=>p20[k]||0),backgroundColor:'#94a3b8',borderRadius:6,categoryPercentage:.72,barPercentage:.72},{label:'2024',data:labels.map(k=>p24[k]||0),backgroundColor:'#2563eb',borderRadius:6,categoryPercentage:.72,barPercentage:.72}]},options:{...opts(),indexAxis:'y',layout:{padding:{right:20}},scales:{x:{beginAtZero:true,grid:{color:'#edf2f7'},ticks:{callback:v=>fmt(v)}},y:{grid:{display:false},ticks:{font:{weight:'700'}}}}}});const all=[...new Set([...Object.keys(p20),...Object.keys(p24)])].map(k=>({p:k,a:p20[k]||0,b:p24[k]||0})).map(x=>({...x,d:x.b-x.a,pc:x.a?100*(x.b-x.a)/x.a:null})).sort((x,y)=>y.b-x.b);document.getElementById('evo-party-table').innerHTML=`<div class="evo-table-wrap" style="margin-top:18px;max-height:380px"><table class="evo-table"><thead><tr><th>Partido</th><th>2020</th><th>2024</th><th>Variação abs.</th><th>Variação %</th></tr></thead><tbody>${all.map(x=>`<tr><td><strong>${esc(x.p)}</strong></td><td>${fmt(x.a)}</td><td>${fmt(x.b)}</td><td class="${x.d>0?'evo-pos':x.d<0?'evo-neg':'evo-neutral'}">${x.d>0?'+':''}${fmt(x.d)}</td><td class="${x.pc>0?'evo-pos':x.pc<0?'evo-neg':'evo-neutral'}">${x.pc==null?'—':(x.pc>0?'+':'')+pct(x.pc)}</td></tr>`).join('')}</tbody></table></div>`}
function drawSlope(rep){const top=[...rep].sort((a,b)=>b.delta-a.delta).slice(0,15);const host=document.getElementById('evo-slope');if(!top.length){host.textContent='Nenhum candidato coincidente entre as bases.';return}const W=1100,H=Math.max(560,top.length*38+70),left=300,right=820,topY=34,row=36;const max=Math.max(...top.flatMap(x=>[x.v20,x.v24]),1);const x=v=>left+(right-left)*(v/max);const rows=top.map((d,i)=>{const y=topY+i*row;return `<text x="8" y="${y+5}" font-size="12" fill="#334155" font-weight="700">${esc(d.nome.length>36?d.nome.slice(0,35)+'…':d.nome)}</text><line x1="${x(d.v20)}" y1="${y}" x2="${x(d.v24)}" y2="${y}" stroke="${d.delta>=0?'#2563eb':'#ef4444'}" stroke-width="3" opacity=".7"/><circle cx="${x(d.v20)}" cy="${y}" r="5" fill="#94a3b8"/><circle cx="${x(d.v24)}" cy="${y}" r="6" fill="#2563eb"/><text x="${x(d.v20)-8}" y="${y-9}" text-anchor="end" font-size="10" fill="#64748b">${fmt(d.v20)}</text><text x="${x(d.v24)+9}" y="${y-9}" font-size="10" fill="#0f172a" font-weight="700">${fmt(d.v24)} • ${esc(d.p24)}</text>`}).join('');host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" width="100%" height="100%" preserveAspectRatio="xMinYMin meet"><text x="${left}" y="18" font-size="11" fill="#64748b">2020</text><text x="${right}" y="18" font-size="11" fill="#64748b">2024</text>${rows}</svg>`}
function miniTable(title,data){return `<div><div class="evo-section-title">${title}</div><div class="evo-table-wrap"><table class="evo-table"><thead><tr><th>Candidato</th><th>2020</th><th>2024</th><th>Δ votos</th><th>Δ %</th><th>Partido 2024</th></tr></thead><tbody>${data.map(x=>`<tr><td><strong>${esc(x.nome)}</strong></td><td>${fmt(x.v20)}</td><td>${fmt(x.v24)}</td><td class="${x.delta>=0?'evo-pos':'evo-neg'}">${x.delta>0?'+':''}${fmt(x.delta)}</td><td class="${x.pct>=0?'evo-pos':'evo-neg'}">${x.pct==null?'—':(x.pct>0?'+':'')+pct(x.pct)}</td><td>${esc(x.p24)}</td></tr>`).join('')}</tbody></table></div></div>`}
function drawTables(rep){const gains=[...rep].sort((a,b)=>b.delta-a.delta).slice(0,10),loss=[...rep].sort((a,b)=>a.delta-b.delta).slice(0,10);document.getElementById('evo-gain-loss').innerHTML=miniTable('10 maiores aumentos de votos',gains)+miniTable('10 maiores quedas de votos',loss)}
function drawRenew(el20,el24,reeleitos,novos){destroy('renew');charts.renew=new Chart(document.getElementById('evo-renew'),{type:'doughnut',data:{labels:['Reeleitos','Renovação'],datasets:[{data:[reeleitos,novos],backgroundColor:['#2563eb','#10b981'],borderColor:'#fff',borderWidth:4}]},options:{...opts(),cutout:'67%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,pointStyle:'circle',padding:16}},tooltip:{callbacks:{label:c=>{const t=reeleitos+novos;return ` ${c.label}: ${fmt(c.raw)} (${pct(t?100*c.raw/t:0)})`}}}}}})}
function drawStatus(){destroy('status');const calc=rows=>{let e=0,n=0;rows.forEach(r=>(elected(r)?e+=votes(r):n+=votes(r)));const t=e+n;return{e,n,ep:t?100*e/t:0,np:t?100*n/t:0}};const a=calc(d20),b=calc(d24);charts.status=new Chart(document.getElementById('evo-status'),{type:'bar',data:{labels:['2020','2024'],datasets:[{label:'Votos em candidatos eleitos',data:[a.ep,b.ep],backgroundColor:'#2563eb',borderRadius:7},{label:'Votos em candidatos não eleitos',data:[a.np,b.np],backgroundColor:'#cbd5e1',borderRadius:7}]},options:{...opts(),scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,min:0,max:100,ticks:{callback:v=>pct(v)},grid:{color:'#edf2f7'}}},plugins:{...opts().plugins,tooltip:{callbacks:{label:c=>` ${c.dataset.label}: ${pct(c.raw)}`}}}}})}
function init(){css();ensurePage();ensureNav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
