(()=>{
'use strict';
const FILES={2016:'cand_mais_votado-municipio_vereador_2016_sc_itajai.csv',2020:'cand_mais_votado-municipio_vereador_2020_sc_itajai.csv',2024:'cand_mais_votado-municipio_vereador_2024_sc_itajai.csv'};const D={};const charts={};
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toUpperCase();const num=v=>Number(String(v??0).replace(/\./g,'').replace(',','.'))||0;const fmt=v=>new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(num(v));const pct=v=>`${fmt(v)}%`;const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function parseCSV(text){const out=[];let r=[],c='',q=false;for(let i=0;i<text.length;i++){const x=text[i],nx=text[i+1];if(x==='"'){if(q&&nx==='"'){c+='"';i++}else q=!q}else if(x===';'&&!q){r.push(c);c=''}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&nx==='\n')i++;r.push(c);c='';if(r.some(v=>v!==''))out.push(r);r=[]}else c+=x}if(c||r.length){r.push(c);out.push(r)}const h=(out.shift()||[]).map(x=>x.replace(/^\uFEFF/,'').trim());return out.map(a=>Object.fromEntries(h.map((k,i)=>[k,String(a[i]??'').trim()]))) }
const votes=r=>num(r.qt_votos_nom_validos), party=r=>r.sg_partido||'SEM PARTIDO', name=r=>r.nm_candidato||'NÃO INFORMADO', elected=r=>/^Eleito/i.test(String(r.ds_sit_tot_turno||'').trim());
function css(){if(document.getElementById('evo-v2-css'))return;const l=document.createElement('link');l.id='evo-v2-css';l.rel='stylesheet';l.href='evolution-v2.css?v=1';document.head.appendChild(l)}
function ensureNav(){let b=document.getElementById('nav-evolution');if(!b){const nav=document.querySelector('header nav');if(!nav)return;b=document.createElement('button');b.id='nav-evolution';b.className='nav-btn analytics-nav';nav.appendChild(b)}b.textContent='Evolução 2016–2024';b.onclick=()=>show(b)}
function ensurePage(){let s=document.getElementById('tab-evolution');if(s)s.remove();s=document.createElement('section');s.id='tab-evolution';s.className='tab-content';s.innerHTML='<div class="e2-page"><div class="e2-head"><span>ELEIÇÕES MUNICIPAIS • VEREADOR</span><h2>Evolução Eleitoral 2016–2024</h2><p>Comparação descritiva de votos nominais por partido e candidatura em três eleições municipais de Itajaí.</p></div><div id="e2-body">Carregando resultados…</div></div>';document.body.appendChild(s);return s}
function show(btn){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));ensurePage().classList.add('active');btn.classList.add('active');load()}
async function load(){if(D[2016])return render();try{const yrs=[2016,2020,2024],rs=await Promise.all(yrs.map(y=>fetch(`${FILES[y]}?v=2`,{cache:'no-store'})));if(rs.some(r=>!r.ok))throw new Error('CSV');for(let i=0;i<yrs.length;i++)D[yrs[i]]=parseCSV(await rs[i].text());render()}catch(e){console.error(e);document.getElementById('e2-body').innerHTML='<div class="e2-card">Não foi possível carregar os resultados.</div>'}}
function allCandidates(){const m=new Map();Object.entries(D).forEach(([y,rows])=>rows.forEach(r=>{const k=norm(name(r));if(!m.has(k))m.set(k,name(r))}));return [...m.entries()].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR'))}function allParties(){return [...new Set(Object.values(D).flat().map(party))].sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function filteredRows(y){const cand=document.getElementById('e2-cand')?.value||'',p=document.getElementById('e2-party')?.value||'';return D[y].filter(r=>(!cand||norm(name(r))===cand)&&(!p||party(r)===p))}
function ptot(y){const m={};filteredRows(y).forEach(r=>m[party(r)]=(m[party(r)]||0)+votes(r));return m}function destroy(id){if(charts[id]){charts[id].destroy();delete charts[id]}}
function selectedYears(){const y=document.getElementById('e2-year')?.value||'';return y?[+y]:[2016,2020,2024]}
function candidateMatrix(){const m=new Map();[2016,2020,2024].forEach(y=>filteredRows(y).forEach(r=>{const k=norm(name(r));if(!m.has(k))m.set(k,{nome:name(r),years:{}});m.get(k).years[y]={v:votes(r),p:party(r),e:elected(r)}}));return [...m.values()]}
function opts(){return{responsive:true,maintainAspectRatio:false,animation:{duration:350},plugins:{legend:{labels:{usePointStyle:true,pointStyle:'circle',padding:16,font:{size:11}}},tooltip:{backgroundColor:'#0f172a',padding:10,callbacks:{label:c=>` ${c.dataset.label}: ${fmt(c.raw)}`}}}}}
function render(){const cands=allCandidates(),parts=allParties();const b=document.getElementById('e2-body');b.innerHTML=`<div class="e2-filters"><select id="e2-year"><option value="">Ano: Todos</option><option>2016</option><option>2020</option><option>2024</option></select><select id="e2-party"><option value="">Partido: Todos</option>${parts.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="e2-cand"><option value="">Candidato: Todos</option>${cands.map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join('')}</select><button id="e2-clear">Limpar filtros</button></div><div class="e2-kpis"><div><span>Votos nominais 2016</span><strong id="e2-k16">—</strong></div><div><span>Votos nominais 2020</span><strong id="e2-k20">—</strong></div><div><span>Votos nominais 2024</span><strong id="e2-k24">—</strong></div><div><span>Variação 2020 → 2024</span><strong id="e2-kvar">—</strong></div></div><div class="e2-grid"><article class="e2-card wide"><h3>Força dos partidos</h3><p>Comparação do volume nominal por legenda nos anos selecionados.</p><div class="e2-chart party"><canvas id="evo-party-v2"></canvas></div><div id="e2-party-table"></div></article><article class="e2-card wide"><h3>Evolução individual das candidaturas</h3><p>Votos em 2016, 2020 e 2024 para candidaturas que aparecem em mais de uma eleição.</p><div id="e2-candidate-table"></div></article><article class="e2-card"><h3>Renovação 2016 → 2020</h3><div class="e2-chart"><canvas id="evo-renew-20"></canvas></div></article><article class="e2-card"><h3>Renovação 2020 → 2024</h3><div class="e2-chart"><canvas id="evo-renew-24"></canvas></div></article></div>`;['e2-year','e2-party','e2-cand'].forEach(id=>document.getElementById(id).onchange=update);document.getElementById('e2-clear').onclick=()=>{['e2-year','e2-party','e2-cand'].forEach(id=>document.getElementById(id).value='');update()};update()}
function update(){const totals={};[2016,2020,2024].forEach(y=>totals[y]=filteredRows(y).reduce((s,r)=>s+votes(r),0));document.getElementById('e2-k16').textContent=fmt(totals[2016]);document.getElementById('e2-k20').textContent=fmt(totals[2020]);document.getElementById('e2-k24').textContent=fmt(totals[2024]);document.getElementById('e2-kvar').textContent=totals[2020]?`${totals[2024]-totals[2020]>=0?'+':''}${pct(100*(totals[2024]-totals[2020])/totals[2020])}`:'—';drawParty();drawCandidates();drawRenew(2016,2020,'renew20','evo-renew-20');drawRenew(2020,2024,'renew24','evo-renew-24')}
function drawParty(){destroy('party');const ys=selectedYears(),maps=Object.fromEntries([2016,2020,2024].map(y=>[y,ptot(y)]));const all=[...new Set(ys.flatMap(y=>Object.keys(maps[y])))];const score=p=>Math.max(...ys.map(y=>maps[y][p]||0));const labels=all.sort((a,b)=>score(b)-score(a)).slice(0,14);const colors={2016:'#94a3b8',2020:'#06b6d4',2024:'#2563eb'};charts.party=new Chart(document.getElementById('evo-party-v2'),{type:'bar',data:{labels,datasets:ys.map(y=>({label:String(y),data:labels.map(p=>maps[y][p]||0),backgroundColor:colors[y],borderRadius:6,categoryPercentage:.7,barPercentage:.7}))},options:{...opts(),indexAxis:'y',layout:{padding:{right:70}},scales:{x:{beginAtZero:true,grid:{color:'#eef2f7'},ticks:{callback:v=>fmt(v)}},y:{grid:{display:false},ticks:{font:{weight:'700'}}}}}});document.getElementById('e2-party-table').innerHTML=`<div class="e2-table-wrap"><table><thead><tr><th>Partido</th><th>2016</th><th>2020</th><th>2024</th><th>Δ 20–16</th><th>Δ 24–20</th></tr></thead><tbody>${[...new Set(Object.keys(maps[2016]).concat(Object.keys(maps[2020]),Object.keys(maps[2024])))].map(p=>{const a=maps[2016][p]||0,b=maps[2020][p]||0,c=maps[2024][p]||0;return{p,a,b,c,d1:b-a,d2:c-b}}).sort((x,y)=>y.c-x.c).map(x=>`<tr><td><strong>${esc(x.p)}</strong></td><td>${fmt(x.a)}</td><td>${fmt(x.b)}</td><td>${fmt(x.c)}</td><td class="${x.d1>=0?'pos':'neg'}">${x.d1>0?'+':''}${fmt(x.d1)}</td><td class="${x.d2>=0?'pos':'neg'}">${x.d2>0?'+':''}${fmt(x.d2)}</td></tr>`).join('')}</tbody></table></div>`}
function drawCandidates(){const arr=candidateMatrix().filter(x=>Object.keys(x.years).length>1).map(x=>{const v16=x.years[2016]?.v??null,v20=x.years[2020]?.v??null,v24=x.years[2024]?.v??null;return{...x,v16,v20,v24,d1:v16!=null&&v20!=null?v20-v16:null,d2:v20!=null&&v24!=null?v24-v20:null}}).sort((a,b)=>(b.d2??-999999)-(a.d2??-999999));const top=arr.slice(0,30);document.getElementById('e2-candidate-table').innerHTML=`<div class="e2-table-wrap candidates"><table><thead><tr><th>Candidato</th><th>Partido 2024</th><th>2016</th><th>2020</th><th>2024</th><th>Δ 20–16</th><th>Δ 24–20</th></tr></thead><tbody>${top.map(x=>`<tr><td><strong>${esc(x.nome)}</strong></td><td>${esc(x.years[2024]?.p||'—')}</td><td>${x.v16==null?'—':fmt(x.v16)}</td><td>${x.v20==null?'—':fmt(x.v20)}</td><td>${x.v24==null?'—':fmt(x.v24)}</td><td class="${x.d1==null?'':x.d1>=0?'pos':'neg'}">${x.d1==null?'—':(x.d1>0?'+':'')+fmt(x.d1)}</td><td class="${x.d2==null?'':x.d2>=0?'pos':'neg'}">${x.d2==null?'—':(x.d2>0?'+':'')+fmt(x.d2)}</td></tr>`).join('')}</tbody></table></div>`}
function drawRenew(y0,y1,key,id){destroy(key);const old=new Set(filteredRows(y0).filter(elected).map(r=>norm(name(r)))),now=filteredRows(y1).filter(elected);const re=now.filter(r=>old.has(norm(name(r)))).length,novo=now.length-re;charts[key]=new Chart(document.getElementById(id),{type:'doughnut',data:{labels:['Reeleitos','Renovação'],datasets:[{data:[re,novo],backgroundColor:['#2563eb','#10b981'],borderColor:'#fff',borderWidth:4}]},options:{...opts(),cutout:'68%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,pointStyle:'circle',padding:14}},tooltip:{callbacks:{label:c=>{const t=re+novo;return ` ${c.label}: ${fmt(c.raw)} (${pct(t?100*c.raw/t:0)})`}}}}}})}
function init(){css();ensureNav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();