(()=>{
const modules=[
 {id:'tab-educacao',label:'Educação',icon:'🎓',title:'Educação e Rede Escolar',desc:'Análises territoriais da rede de ensino, distribuição das unidades educacionais e relação com a população residente.',items:['Mapa das unidades de ensino','Indicadores educacionais e acessibilidade']},
 {id:'tab-saude',label:'Saúde',icon:'✚',title:'Saúde e Serviços',desc:'Leitura espacial da oferta de serviços de saúde e da distribuição territorial dos equipamentos públicos e conveniados.',items:['Mapa das unidades de saúde']},
 {id:'tab-mobilidade',label:'Mobilidade',icon:'↔',title:'Mobilidade e Acessibilidade',desc:'Análises de deslocamento, acessibilidade e conexão entre população, serviços e equipamentos urbanos.',items:['Rede viária e transporte coletivo','Tempo e distância de acesso aos serviços','Áreas com menor acessibilidade']},
 {id:'tab-vulnerabilidade',label:'Vulnerabilidade',icon:'◉',title:'Vulnerabilidade Socioespacial',desc:'Integração de indicadores demográficos e territoriais para apoiar a leitura das desigualdades socioespaciais do município.',items:['População e densidade demográfica','Renda e características domiciliares']},
 {id:'tab-riscos',label:'Riscos & Resiliência',icon:'△',title:'Riscos e Resiliência Territorial',desc:'Análises espaciais voltadas à exposição da população, infraestrutura e serviços a eventos adversos e situações de risco.',items:['Áreas suscetíveis a inundação','População e equipamentos expostos','Indicadores de resiliência territorial']}
];
function injectStyle(){if(document.getElementById('future-modules-style'))return;const s=document.createElement('style');s.id='future-modules-style';s.textContent=`
.future-page{max-width:1180px;margin:0 auto;padding:42px 30px 70px}.future-hero{background:linear-gradient(135deg,#0f172a,#172554);border-radius:20px;padding:44px;color:white;position:relative;overflow:hidden;box-shadow:0 18px 38px -28px rgba(15,23,42,.7)}.future-hero:after{content:'';position:absolute;width:260px;height:260px;border-radius:50%;right:-90px;top:-120px;background:rgba(59,130,246,.18)}.future-badge{display:inline-flex;align-items:center;gap:7px;padding:7px 11px;border-radius:999px;background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.15);font-size:11px;font-weight:800;letter-spacing:.6px;text-transform:uppercase;color:#bfdbfe;margin-bottom:18px}.future-hero h2{font-size:34px;line-height:1.1;margin:0 0 14px;position:relative;z-index:1}.future-hero p{max-width:760px;color:#cbd5e1;line-height:1.7;font-size:14px;position:relative;z-index:1}.future-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:22px}.future-card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:22px;box-shadow:0 8px 24px -22px rgba(15,23,42,.45)}.future-card strong{display:block;color:#0f172a;font-size:14px;margin-bottom:5px}.future-card span{font-size:12px;color:#64748b;line-height:1.5}.future-nav{white-space:nowrap}.nav-btn.future-nav::before{content:'•';margin-right:6px;color:#94a3b8}.nav-btn.future-nav.active::before{color:#2563eb}@media(max-width:700px){.future-page{padding:22px 15px 48px}.future-hero{padding:28px 22px;border-radius:16px}.future-hero h2{font-size:26px}.future-grid{grid-template-columns:1fr}.future-card{padding:18px}.future-hero p{font-size:13px}}
`;document.head.appendChild(s)}
function show(id,btn){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));const el=document.getElementById(id);if(el)el.classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));btn?.classList.add('active')}
function removeMarkedHomeKpi(){document.querySelectorAll('.kpi-card').forEach(card=>{const txt=(card.textContent||'').toLowerCase();if(txt.includes('biometria cadastrada'))card.remove()})}
function build(){injectStyle();removeMarkedHomeKpi();const nav=document.querySelector('header nav');if(!nav)return;modules.forEach(m=>{if(document.getElementById(m.id))return;const b=document.createElement('button');b.className='nav-btn future-nav';b.type='button';b.textContent=m.label;b.onclick=()=>show(m.id,b);nav.appendChild(b);const sec=document.createElement('section');sec.id=m.id;sec.className='tab-content';sec.innerHTML=`<div class="future-page"><div class="future-hero"><div class="future-badge">${m.icon} Em desenvolvimento</div><h2>${m.title}</h2><p>${m.desc}</p></div><div class="future-grid">${m.items.map((x,i)=>`<div class="future-card"><strong>${String(i+1).padStart(2,'0')} · ${x}</strong><span>Este componente será integrado ao Atlas conforme as bases territoriais forem consolidadas e validadas.</span></div>`).join('')}</div></div>`;document.body.appendChild(sec)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();