(()=>{
'use strict';
function css(){if(document.getElementById('atlas-request-css'))return;const s=document.createElement('style');s.id='atlas-request-css';s.textContent=`
.auth-request-button{width:100%;height:42px;margin-top:10px;border:1px solid #cbd5e1;border-radius:9px;background:#f8fafc;color:#334155;font-size:11px;font-weight:800;cursor:pointer}.auth-request-help{margin-top:10px;font-size:9.5px;line-height:1.5;color:#94a3b8;text-align:center}.auth-request-box{display:none;margin-top:12px;padding:12px;border:1px solid #dbe3ef;border-radius:10px;background:#f8fafc}.auth-request-box.open{display:block}.auth-request-box input{width:100%;height:40px;margin-top:8px;padding:0 10px;border:1px solid #cbd5e1;border-radius:8px;font-size:12px;background:#fff}.auth-request-send{width:100%;height:40px;margin-top:10px;border:0;border-radius:8px;background:#2563eb;color:#fff;font-size:11px;font-weight:800;cursor:pointer}.auth-request-send:disabled{opacity:.65;cursor:wait}.auth-request-ok{color:#166534!important;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:10px!important;min-height:auto!important;line-height:1.45}.auth-request-error{color:#991b1b!important;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:10px!important;min-height:auto!important;line-height:1.45}.auth-request-title{font-size:11px;font-weight:800;color:#0f172a}.auth-request-note{font-size:9.5px;color:#64748b;line-height:1.45;margin-top:4px}
`;document.head.appendChild(s)}
function msg(text,type='ok'){if(typeof setAuthMessage==='function')setAuthMessage(text);const el=document.getElementById('auth-message');if(el){el.classList.remove('auth-request-ok','auth-request-error');el.classList.add(type==='error'?'auth-request-error':'auth-request-ok')}}
function montar(){css();const login=document.getElementById('google-login-button');if(!login||document.getElementById('request-access-button'))return;const b=document.createElement('button');b.id='request-access-button';b.className='auth-request-button';b.type='button';b.textContent='Solicitar acesso';login.insertAdjacentElement('afterend',b);const box=document.createElement('div');box.id='request-access-box';box.className='auth-request-box';box.innerHTML=`<div class="auth-request-title">Solicitar acesso ao Atlas</div><div class="auth-request-note">Informe seu nome e o e-mail da conta Google que será utilizada para entrar.</div><input id="request-name" type="text" autocomplete="name" placeholder="Seu nome"><input id="request-email" type="email" autocomplete="email" placeholder="seuemail@gmail.com"><button id="request-send" class="auth-request-send" type="button">Enviar solicitação</button>`;b.insertAdjacentElement('afterend',box);const help=document.createElement('div');help.className='auth-request-help';help.textContent='Depois do envio, a solicitação ficará aguardando aprovação do administrador.';box.insertAdjacentElement('afterend',help);b.onclick=()=>box.classList.toggle('open');document.getElementById('request-send').onclick=enviar;const footer=document.querySelector('.auth-footer');if(footer)footer.textContent='O acesso à plataforma depende de aprovação administrativa.'}
async function enviar(){const nome=(document.getElementById('request-name')?.value||'').trim();const email=(document.getElementById('request-email')?.value||'').trim().toLowerCase();const btn=document.getElementById('request-send');if(nome.length<2){msg('Informe seu nome para enviar a solicitação.','error');return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){msg('Informe um e-mail Google válido.','error');return}btn.disabled=true;btn.textContent='Enviando…';try{const {error}=await supabaseClient.rpc('solicitar_acesso_publico',{p_nome:nome,p_email:email});if(error)throw error;msg('Solicitação enviada com sucesso. Seu acesso está sendo analisado pelo administrador. Assim que a solicitação for aprovada, entre com essa mesma conta Google.','ok');document.getElementById('request-access-box')?.classList.remove('open');}catch(e){console.error('Erro ao solicitar acesso:',e);msg('Não foi possível enviar sua solicitação. Tente novamente.','error')}finally{btn.disabled=false;btn.textContent='Enviar solicitação'}}
function boot(){montar()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();