(()=>{
'use strict';
const KEY='atlas_access_request';
let processando=false;
function css(){if(document.getElementById('atlas-request-css'))return;const s=document.createElement('style');s.id='atlas-request-css';s.textContent=`
.auth-request-button{width:100%;height:42px;margin-top:10px;border:1px solid #cbd5e1;border-radius:9px;background:#f8fafc;color:#334155;font-size:11px;font-weight:800;cursor:pointer;transition:.18s ease}.auth-request-button:hover{background:#eff6ff;border-color:#93c5fd;color:#1d4ed8}.auth-request-button:disabled{opacity:.65;cursor:wait}.auth-request-help{margin-top:10px;font-size:9.5px;line-height:1.5;color:#94a3b8;text-align:center}.auth-request-ok{color:#166534!important;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:11px!important;min-height:auto!important;line-height:1.5}.auth-request-error{color:#991b1b!important;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:11px!important;min-height:auto!important;line-height:1.5}
`;document.head.appendChild(s)}
function mensagem(texto,tipo='ok'){const msg=document.getElementById('auth-message');if(!msg)return;msg.textContent=texto;msg.classList.remove('auth-request-ok','auth-request-error');msg.classList.add(tipo==='ok'?'auth-request-ok':'auth-request-error')}
function montar(){css();const login=document.getElementById('google-login-button');if(!login||document.getElementById('request-access-button'))return;const b=document.createElement('button');b.id='request-access-button';b.className='auth-request-button';b.type='button';b.textContent='Solicitar acesso';b.onclick=solicitar;login.insertAdjacentElement('afterend',b);const help=document.createElement('div');help.className='auth-request-help';help.textContent='Ainda não possui autorização? Identifique-se com sua conta Google e envie uma solicitação ao administrador.';b.insertAdjacentElement('afterend',help);const footer=document.querySelector('.auth-footer');if(footer)footer.textContent='O acesso à plataforma depende de aprovação administrativa.'}
async function solicitar(){localStorage.setItem(KEY,'1');const b=document.getElementById('request-access-button');if(b){b.disabled=true;b.textContent='Abrindo Google…'}try{if(typeof entrarComGoogle==='function')await entrarComGoogle();else throw new Error('Login Google indisponível')}catch(e){localStorage.removeItem(KEY);if(b){b.disabled=false;b.textContent='Solicitar acesso'}mensagem('Não foi possível iniciar a solicitação. Tente novamente.','erro');console.error(e)}}
async function registrarSolicitacao(){if(processando||localStorage.getItem(KEY)!=='1'||typeof supabaseClient==='undefined')return;processando=true;try{const {data:{session},error:sessionError}=await supabaseClient.auth.getSession();if(sessionError)throw sessionError;if(!session?.user){processando=false;return}const {error}=await supabaseClient.rpc('solicitar_acesso_atlas');if(error)throw error;localStorage.removeItem(KEY);mensagem('Solicitação enviada com sucesso. Seu acesso está sendo analisado pelo administrador. Assim que a solicitação for aprovada, você poderá entrar no Atlas.');const b=document.getElementById('request-access-button');if(b){b.disabled=false;b.textContent='Solicitar acesso'}setTimeout(async()=>{try{await supabaseClient.auth.signOut()}catch(e){}},900)}catch(e){console.error('Falha ao registrar solicitação:',e);mensagem('Sua conta Google foi identificada, mas não foi possível registrar a solicitação. Tente novamente.','erro');const b=document.getElementById('request-access-button');if(b){b.disabled=false;b.textContent='Tentar novamente'}processando=false}}
function boot(){montar();registrarSolicitacao();if(typeof supabaseClient!=='undefined')supabaseClient.auth.onAuthStateChange((event,session)=>{if((event==='SIGNED_IN'||event==='INITIAL_SESSION')&&session?.user)setTimeout(registrarSolicitacao,50)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();