(()=>{
'use strict';
const KEY='atlas_access_request';
function css(){if(document.getElementById('atlas-request-css'))return;const s=document.createElement('style');s.id='atlas-request-css';s.textContent=`
.auth-request-button{width:100%;height:42px;margin-top:10px;border:1px solid #cbd5e1;border-radius:9px;background:#f8fafc;color:#334155;font-size:11px;font-weight:800;cursor:pointer;transition:.18s ease}.auth-request-button:hover{background:#eff6ff;border-color:#93c5fd;color:#1d4ed8}.auth-request-help{margin-top:10px;font-size:9.5px;line-height:1.5;color:#94a3b8;text-align:center}.auth-request-ok{color:#166534!important;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:10px!important;min-height:auto!important}.adm-badge{display:inline-flex;align-items:center;justify-content:center;min-width:18px;height:18px;margin-left:5px;padding:0 5px;border-radius:999px;background:#dc2626;color:#fff;font-size:9px;font-weight:800;vertical-align:middle}
`;document.head.appendChild(s)}
function montar(){css();const login=document.getElementById('google-login-button');if(!login||document.getElementById('request-access-button'))return;const b=document.createElement('button');b.id='request-access-button';b.className='auth-request-button';b.type='button';b.textContent='Solicitar acesso';b.onclick=solicitar;login.insertAdjacentElement('afterend',b);const help=document.createElement('div');help.className='auth-request-help';help.textContent='Ainda não possui autorização? Identifique-se com sua conta Google e envie uma solicitação ao administrador.';b.insertAdjacentElement('afterend',help);const footer=document.querySelector('.auth-footer');if(footer)footer.textContent='O acesso à plataforma depende de aprovação administrativa.'}
async function solicitar(){localStorage.setItem(KEY,'1');const b=document.getElementById('request-access-button');if(b){b.disabled=true;b.textContent='Abrindo Google…'}try{if(typeof entrarComGoogle==='function')await entrarComGoogle();else throw new Error('Login Google indisponível')}catch(e){localStorage.removeItem(KEY);if(b){b.disabled=false;b.textContent='Solicitar acesso'}console.error(e)}}
function observar(){const msg=document.getElementById('auth-message');if(!msg)return;new MutationObserver(()=>{if(localStorage.getItem(KEY)!=='1')return;const t=(msg.textContent||'').toLowerCase();if(t.includes('autenticada')||t.includes('validar o acesso')||t.includes('não autorizado')){msg.textContent='Solicitação enviada. Sua conta foi identificada e está aguardando aprovação de um administrador.';msg.classList.add('auth-request-ok');localStorage.removeItem(KEY);const b=document.getElementById('request-access-button');if(b){b.disabled=false;b.textContent='Solicitar acesso'}}}).observe(msg,{childList:true,characterData:true,subtree:true})}
function boot(){montar();observar()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();