(()=>{
'use strict';
const charts={};let rows=null;let loaded=false;
const F={ano:'Ano de eleição',raca:'Cor / Raça',civil:'Estado civil',idade:'Faixa etária',genero:'Gênero',instrucao:'Grau de instrução',turno:'Turno',municipio:'Município',aptos:'Quantidade de eleitores aptos',comp:'Quantidade de eleitores comparecimento',abs:'Quantidade de eleitores abstenção',fac:'Quantidade de eleitores facultativos',obr:'Quantidade de eleitores obrigatórios',compFac:'Quantidade de eleitores comparecimento facultativo',compObr:'Quantidade de eleitores comparecimento obrigatório',absObr:'Quantidade de eleitores abstenção obrigatório'};
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(n)||0));
const pct=n=>`${(Number(n)||0).toFixed(1).replace('.',',')}%`;
const num=v=>{if(v==null||v==='')return 0;return Number(String(v).replace(/\./g,'').replace(',','.'))||0};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function svg(kind){const p={users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',check:'<path d="M20 6 9 17l-5-5"/>',minus:'<circle cx="12" cy="12" r="9"/><path d="M8 12h8"/>',percent:'<circle cx="12" cy="12" r="9"/><path d="m8 16 8-8"/><circle cx="9" cy="9" r="1"/><circle cx="15" cy="15" r="1"/>',party:'<path d="M3 21h18M5 21V9l7-5 7 5v12M9 21v-7h6v7"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',access:'<circle cx="12" cy="4" r="2"/><path d="M5 8h14M12 6v6M9 21l3-9 3 9M8 14l-3 4M16 14l3 4"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${p[kind]||p.users}</svg>`}
function addCss(){if(document.getElementById('turnout-css'))return;const l=document.createElement('link');l.id='turnout-css';l.rel='stylesheet';l.href='turnout.css?v=1';document.head.appendChild(l)}
function parseCSV(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===';'&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))out.push(row);row=[]}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}if(!out.length)return[];const headers=out.shift().map((h,i)=>String(h).replace(/^\uFEFF/,'').trim()||`campo_${i}`);return out.map(r=>{const o={};headers.forEach((h,i)=>o[h]=String(r[i]??'').trim());return o})}
function vals(a,k){return [...new Set(a.map(r=>r[k]).filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),'pt-BR',{numeric:true}))}
function sum(a,k){return a.reduce((s,r)=>s+num(r[k]),0)}
function group2(a,key){const o={};a.forEach(r=>{const k=r[key]||'Não informado';if(!o[k])o[k]={comp:0,abs:0};o[k].comp+=num(r[F.comp]);o[k].abs+=num(r[F.abs])});return o}
function ageStart(s){const m=String(s).match(/\d+/);return m?Number(m[0]):999}
function destroy(id){if(charts[id]){charts[id].destroy();delete charts[id]}}
function ensureNav(){const nav=document.querySelector('header nav');if(!nav||document.getElementById('nav-turnout'))return;const b=document.createElement('button');b.id='nav-turnout';b.className='nav-btn analytics-nav';b.textContent='Comparecimento & Abstenção';b.onclick=()=>showTab(b);nav.appendChild(b)}
function ensurePage(){let root=document.getElementById('tab-turnout');if(root)return root;root=document.createElement('section');root.id='tab-turnout';root.className='tab-content';root.innerHTML=`<div class="turnout-page"><div class="turnout-head"><div><h2>Comparecimento e Abstenção</h2><p>Análise demográfica do comparecimento eleitoral e da abstenção em Itajaí, com recortes por idade, escolaridade, gênero, cor/raça e natureza do voto.</p></div></div><div id="turnout-body" class="turnout-loading">Carregando base de comparecimento e abstenção…</div></div>`;document.body.appendChild(root);return root}
function showTab(btn){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));ensurePage().classList.add('active');btn?.classList.add('active');load()}
async function load(){if(loaded)return render();const body=document.getElementById('turnout-body');try{const res=await fetch(`comparecimento_abstencao.csv?v=2`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);rows=parseCSV(await res.text()); console.info('TURNOUT CSV', {linhas: rows.length, cabecalhos: rows[0] ? Object.keys(rows[0]) : []}); loaded=true;render()}catch(e){console.error('Comparecimento/abstenção:',e);if(body){body.className='turnout-error';body.textContent='Não foi possível carregar a base de comparecimento e abstenção.'}}}
function select(id,label,options){return `<select id="${id}"><option value="">${label}: Todos</option>${options.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select>`}
function kpi(label,id,sub,icon){return `<div class="turnout-kpi"><div class="kpi-icon">${svg(icon)}</div><span>${label}</span><strong id="${id}">—</strong><small>${sub}</small></div>`}
function render(){const body=document.getElementById('turnout-body');if(!body||!rows)return;body.className='';body.innerHTML=`<div class="turnout-filters">${select('ta-ano','Ano',vals(rows,F.ano))}${select('ta-turno','Turno',vals(rows,F.turno))}${select('ta-genero','Gênero',vals(rows,F.genero))}<button class="turnout-clear" id="ta-clear">Limpar filtros</button></div><div class="turnout-kpis">${kpi('Eleitores aptos','ta-k-aptos','base selecionada','users')}${kpi('Comparecimento','ta-k-comp','eleitores','check')}${kpi('Abstenção','ta-k-abs','eleitores','minus')}${kpi('Taxa de abstenção','ta-k-taxa','sobre aptos','percent')}</div><div class="turnout-grid"><div class="turnout-card wide"><h3>Comparecimento x abstenção por faixa etária</h3><p>Barras agrupadas para identificar em quais grupos de idade a ausência eleitoral é mais intensa.</p><div class="turnout-chart tall"><canvas id="ta-age"></canvas></div></div><div class="turnout-card wide"><h3>Comparecimento e abstenção por grau de instrução</h3><p>Barras 100% empilhadas. Cada linha representa a composição percentual dentro do respectivo nível de escolaridade.</p><div class="turnout-chart tall"><canvas id="ta-school"></canvas></div></div><div class="turnout-card"><h3>Mapa de calor demográfico</h3><p>Taxa de abstenção por gênero e cor/raça. Células mais intensas indicam maior proporção de ausências.</p><div id="ta-heat" class="turnout-heatmap-wrap"></div></div><div class="turnout-card"><h3>Voto facultativo x obrigatório</h3><p>Comparecimento e ausência dentro de cada regime de obrigatoriedade do voto.</p><div class="turnout-donuts"><div class="turnout-donut-box"><h4>Voto facultativo</h4><div class="turnout-chart"><canvas id="ta-fac"></canvas></div></div><div class="turnout-donut-box"><h4>Voto obrigatório</h4><div class="turnout-chart"><canvas id="ta-obr"></canvas></div></div></div></div></div>`;['ta-ano','ta-turno','ta-genero'].forEach(id=>document.getElementById(id).onchange=update);document.getElementById('ta-clear').onclick=()=>{['ta-ano','ta-turno','ta-genero'].forEach(id=>document.getElementById(id).value='');update()};update()}
function filtered(){const y=document.getElementById('ta-ano')?.value||'',t=document.getElementById('ta-turno')?.value||'',g=document.getElementById('ta-genero')?.value||'';return rows.filter(r=>(!y||r[F.ano]===y)&&(!t||r[F.turno]===t)&&(!g||r[F.genero]===g))}
function update(){const a=filtered();const apt=sum(a,F.aptos),comp=sum(a,F.comp),abs=sum(a,F.abs);document.getElementById('ta-k-aptos').textContent=fmt(apt);document.getElementById('ta-k-comp').textContent=fmt(comp);document.getElementById('ta-k-abs').textContent=fmt(abs);document.getElementById('ta-k-taxa').textContent=pct(apt?100*abs/apt:0);drawAge(a);drawSchool(a);drawHeat(a);drawDonuts(a)}
function baseOpts(){return{responsive:true,maintainAspectRatio:false,animation:{duration:450},plugins:{legend:{labels:{usePointStyle:true,pointStyle:'circle',boxWidth:9,boxHeight:9,padding:18,font:{size:10}}},tooltip:{backgroundColor:'#0f172a',padding:11,titleFont:{size:11},bodyFont:{size:11}}}}}
function drawAge(a){destroy('ta-age');const o=group2(a,F.idade),entries=Object.entries(o).sort((x,y)=>ageStart(x[0])-ageStart(y[0]));const el=document.getElementById('ta-age');if(!el)return;charts['ta-age']=new Chart(el,{type:'bar',data:{labels:entries.map(x=>x[0]),datasets:[{label:'Comparecimento',data:entries.map(x=>x[1].comp),backgroundColor:'#2563eb',borderRadius:6,categoryPercentage:.68,barPercentage:.72},{label:'Abstenção',data:entries.map(x=>x[1].abs),backgroundColor:'#f59e0b',borderRadius:6,categoryPercentage:.68,barPercentage:.72}]},options:{...baseOpts(),layout:{padding:{top:12,bottom:8}},scales:{x:{grid:{display:false},ticks:{maxRotation:35,minRotation:0,font:{size:10}}},y:{beginAtZero:true,grid:{color:'#edf2f7'},ticks:{callback:v=>fmt(v),font:{size:10}}}}}})}
function drawSchool(a){destroy('ta-school');const o=group2(a,F.instrucao),entries=Object.entries(o).map(([k,v])=>{const z=v.comp+v.abs;return[k,{comp:z?100*v.comp/z:0,abs:z?100*v.abs/z:0,total:z}]}).sort((x,y)=>y[1].total-x[1].total);const el=document.getElementById('ta-school');if(!el)return;const wrap=el.parentElement;if(wrap)wrap.style.height=Math.max(430,entries.length*48+100)+'px';charts['ta-school']=new Chart(el,{type:'bar',data:{labels:entries.map(x=>x[0]),datasets:[{label:'Comparecimento',data:entries.map(x=>x[1].comp),backgroundColor:'#2563eb',borderRadius:5,categoryPercentage:.62,barPercentage:.66},{label:'Abstenção',data:entries.map(x=>x[1].abs),backgroundColor:'#f59e0b',borderRadius:5,categoryPercentage:.62,barPercentage:.66}]},options:{...baseOpts(),indexAxis:'y',scales:{x:{stacked:true,min:0,max:100,grid:{color:'#edf2f7'},ticks:{callback:v=>`${v}%`,font:{size:10}}},y:{stacked:true,grid:{display:false},ticks:{font:{size:10},autoSkip:false}}},plugins:{...baseOpts().plugins,tooltip:{callbacks:{label:c=>` ${c.dataset.label}: ${pct(c.raw)}`}}}}})}
function drawHeat(a){const genders=vals(a,F.genero),races=vals(a,F.raca);const matrix={};let max=0;genders.forEach(g=>races.forEach(r=>matrix[`${g}|${r}`]={comp:0,abs:0}));a.forEach(x=>{const k=`${x[F.genero]||'Não informado'}|${x[F.raca]||'Não informado'}`;if(!matrix[k])matrix[k]={comp:0,abs:0};matrix[k].comp+=num(x[F.comp]);matrix[k].abs+=num(x[F.abs])});Object.values(matrix).forEach(v=>{const z=v.comp+v.abs;v.rate=z?100*v.abs/z:0;max=Math.max(max,v.rate)});const html=`<table class="turnout-heatmap"><thead><tr><th>Gênero</th>${races.map(r=>`<th>${esc(r)}</th>`).join('')}</tr></thead><tbody>${genders.map(g=>`<tr><th>${esc(g)}</th>${races.map(r=>{const v=matrix[`${g}|${r}`]||{rate:0,abs:0};const alpha=max?(.10+.75*v.rate/max):.1;return `<td style="background:rgba(245,158,11,${alpha.toFixed(2)})">${pct(v.rate)}<small>${fmt(v.abs)} ausências</small></td>`}).join('')}</tr>`).join('')}</tbody></table>`;const el=document.getElementById('ta-heat');if(el)el.innerHTML=html}
function donut(id,comp,abs){destroy(id);const el=document.getElementById(id);if(!el)return;charts[id]=new Chart(el,{type:'doughnut',data:{labels:['Comparecimento','Abstenção'],datasets:[{data:[Math.max(0,comp),Math.max(0,abs)],backgroundColor:['#2563eb','#f59e0b'],borderColor:'#fff',borderWidth:4,hoverOffset:5}]},options:{...baseOpts(),cutout:'68%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,pointStyle:'circle',boxWidth:9,padding:12,font:{size:9}}},tooltip:{callbacks:{label:c=>` ${c.label}: ${fmt(c.raw)}`}}}}})}
function drawDonuts(a){const fac=sum(a,F.fac),compFac=sum(a,F.compFac),absFac=Math.max(0,fac-compFac);const obr=sum(a,F.obr),compObr=sum(a,F.compObr),absObrDirect=sum(a,F.absObr),absObr=absObrDirect||Math.max(0,obr-compObr);donut('ta-fac',compFac,absFac);donut('ta-obr',compObr,absObr)}
function enhanceIcons(){document.querySelectorAll('.analytics-kpi').forEach((el,i)=>{if(el.querySelector('.kpi-icon'))return;const text=(el.querySelector('span')?.textContent||'').toLowerCase();let kind=text.includes('partido')?'party':text.includes('10 anos')?'clock':text.includes('defici')?'access':text.includes('biometr')?'check':text.includes('voto')?'check':'users';el.insertAdjacentHTML('afterbegin',`<div class="kpi-icon">${svg(kind)}</div>`)})}
function tuneBars(){if(!window.Chart)return;Object.values(Chart.instances||{}).forEach(ch=>{const id=ch.canvas?.id||'';if(id.startsWith('ta-'))return;if(ch.config.type!=='bar')return;const mobile=matchMedia('(max-width:700px)').matches;ch.data.datasets.forEach(ds=>{ds.categoryPercentage=.58;ds.barPercentage=.68;if(id==='fc-partido'||id==='ec-faixa')ds.barThickness=mobile?15:18});if(id==='fc-partido'){const w=ch.canvas.parentElement;if(w)w.style.height=Math.max(mobile?1180:1060,(ch.data.labels?.length||0)*(mobile?44:38)+120)+'px'}ch.update('none')})}
function init(){addCss();ensureNav();ensurePage();enhanceIcons();setTimeout(()=>{enhanceIcons();tuneBars()},800);new MutationObserver(()=>{enhanceIcons()}).observe(document.body,{childList:true,subtree:true});setInterval(tuneBars,3500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();