(()=>{
'use strict';
const FILE='comparecimento_abstencao.csv';const charts={};let rows=[];
const F={ano:'Ano de eleição',raca:'Cor / Raça',civil:'Estado civil',idade:'Faixa etária',genero:'Gênero',instrucao:'Grau de instrução',turno:'Turno',aptos:'Quantidade de eleitores aptos',comp:'Quantidade de eleitores comparecimento',abs:'Quantidade de eleitores abstenção',fac:'Quantidade de eleitores facultativos',obr:'Quantidade de eleitores obrigatórios',compFac:'Quantidade de eleitores comparecimento facultativo',compObr:'Quantidade de eleitores comparecimento obrigatório',pcdComp:'Quantidade de eleitores deficientes comparecimento',pcdAbs:'Quantidade de eleitores deficientes abstenção'};
const n=v=>Number(String(v??0).replace(/\./g,'').replace(',','.'))||0;const fmt=v=>new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n(v));const pct=v=>`${fmt(v)}%`;const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function parseCSV(text){const out=[];let r=[],c='',q=false;for(let i=0;i<text.length;i++){const x=text[i],nx=text[i+1];if(x==='"'){if(q&&nx==='"'){c+='"';i++}else q=!q}else if(x===';'&&!q){r.push(c);c=''}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&nx==='\n')i++;r.push(c);c='';if(r.some(v=>v!==''))out.push(r);r=[]}else c+=x}if(c||r.length){r.push(c);out.push(r)}const h=(out.shift()||[]).map(x=>x.replace(/^\uFEFF/,'').trim());return out.map(a=>Object.fromEntries(h.map((k,i)=>[k,String(a[i]??'').trim()]))) }
const sum=(a,k)=>a.reduce((s,r)=>s+n(r[k]),0);const vals=(a,k)=>[...new Set(a.map(r=>r[k]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true}));
function ageStart(s){const m=String(s).match(/\d+/);return m?+m[0]:999}function destroy(id){if(charts[id]){charts[id].destroy();delete charts[id]}}
function css(){if(document.getElementById('turnout-v3-css'))return;const l=document.createElement('link');l.id='turnout-v3-css';l.rel='stylesheet';l.href='turnout-v3.css?v=1';document.head.appendChild(l)}
function ensureNav(){let b=document.getElementById('nav-turnout');if(!b){const nav=document.querySelector('header nav');if(!nav)return; b=document.createElement('button');b.id='nav-turnout';b.className='nav-btn analytics-nav';b.textContent='Comparecimento & Abstenção';nav.appendChild(b)}b.onclick=()=>show(b)}
function ensurePage(){let s=document.getElementById('tab-turnout');if(s){s.remove();}s=document.createElement('section');s.id='tab-turnout';s.className='tab-content';s.innerHTML='<div class="ta3-page"><div class="ta3-head"><div><span class="ta3-kicker">ELEIÇÕES • PERFIL DE PARTICIPAÇÃO</span><h2>Comparecimento e Abstenção</h2><p>Leitura estatística do comportamento eleitoral de Itajaí por escolaridade, idade, gênero, voto facultativo e acessibilidade.</p></div></div><div id="ta3-body">Carregando base…</div></div>';document.body.appendChild(s);return s}
function show(btn){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));ensurePage().classList.add('active');btn.classList.add('active');load()}
async function load(){if(rows.length)return render();try{const r=await fetch(`${FILE}?v=3`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);rows=parseCSV(await r.text());render()}catch(e){document.getElementById('ta3-body').innerHTML='<div class="ta3-card">Não foi possível carregar a base.</div>';console.error(e)}}
function sel(id,label,a,k){return `<select id="${id}"><option value="">${label}: Todos</option>${vals(a,k).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select>`}
function render(){const b=document.getElementById('ta3-body');b.innerHTML=`<div class="ta3-filters">${sel('ta3-ano','Ano',rows,F.ano)}${sel('ta3-turno','Turno',rows,F.turno)}${sel('ta3-genero','Gênero',rows,F.genero)}<button id="ta3-clear">Limpar filtros</button></div><div class="ta3-kpis"><div><span>Eleitores aptos</span><strong id="k-apt">—</strong><small>base selecionada</small></div><div><span>Comparecimento</span><strong id="k-comp">—</strong><small>eleitores</small></div><div><span>Abstenção</span><strong id="k-abs">—</strong><small>eleitores</small></div><div><span>Taxa de abstenção</span><strong id="k-rate">—</strong><small>sobre aptos</small></div></div><div class="ta3-grid"><article class="ta3-card wide"><h3>Taxa de abstenção por grau de instrução</h3><p>Percentual relativo dentro de cada nível de escolaridade, ordenado da maior para a menor taxa.</p><div class="ta3-chart school"><canvas id="ta3-school"></canvas></div></article><article class="ta3-card wide"><h3>Faixa etária × gênero</h3><p>Mapa de calor da taxa de abstenção. Quanto mais intensa a célula, maior a proporção de ausências naquele grupo.</p><div id="ta3-heat"></div></article><article class="ta3-card"><h3>Engajamento no voto facultativo</h3><p>Comparecimento relativo dos extremos etários em que o voto é facultativo.</p><div class="ta3-chart"><canvas id="ta3-fac"></canvas></div></article><article class="ta3-card"><h3>Acessibilidade e inclusão (PCD)</h3><p>Comparação da taxa de abstenção do eleitorado PCD com a taxa geral da base selecionada.</p><div class="ta3-chart"><canvas id="ta3-pcd"></canvas></div></article><article class="ta3-card wide"><h3>Comparecimento x abstenção por faixa etária</h3><p>Volume absoluto por grupo etário.</p><div class="ta3-chart tall"><canvas id="ta3-age"></canvas></div></article></div>`;['ta3-ano','ta3-turno','ta3-genero'].forEach(id=>document.getElementById(id).onchange=update);document.getElementById('ta3-clear').onclick=()=>{['ta3-ano','ta3-turno','ta3-genero'].forEach(id=>document.getElementById(id).value='');update()};update()}
function filtered(){const y=document.getElementById('ta3-ano')?.value||'',t=document.getElementById('ta3-turno')?.value||'',g=document.getElementById('ta3-genero')?.value||'';return rows.filter(r=>(!y||r[F.ano]===y)&&(!t||r[F.turno]===t)&&(!g||r[F.genero]===g))}
function group(a,k){const o={};a.forEach(r=>{const z=r[k]||'Não informado';o[z]??={comp:0,abs:0};o[z].comp+=n(r[F.comp]);o[z].abs+=n(r[F.abs])});return o}
function base(){return{responsive:true,maintainAspectRatio:false,animation:{duration:350},plugins:{legend:{labels:{usePointStyle:true,pointStyle:'circle',padding:16,font:{size:11}}},tooltip:{backgroundColor:'#0f172a',padding:10}}}}
function update(){const a=filtered(),apt=sum(a,F.aptos),comp=sum(a,F.comp),abs=sum(a,F.abs);document.getElementById('k-apt').textContent=fmt(apt);document.getElementById('k-comp').textContent=fmt(comp);document.getElementById('k-abs').textContent=fmt(abs);document.getElementById('k-rate').textContent=pct(apt?100*abs/apt:0);drawSchool(a);drawHeat(a);drawFac(a);drawPcd(a);drawAge(a)}
function drawSchool(a){destroy('school');const entries=Object.entries(group(a,F.instrucao)).map(([k,v])=>({k,...v,rate:(v.comp+v.abs)?100*v.abs/(v.comp+v.abs):0,total:v.comp+v.abs})).sort((x,y)=>y.rate-x.rate);const c=document.getElementById('ta3-school');c.parentElement.style.height=Math.max(430,entries.length*46+80)+'px';charts.school=new Chart(c,{type:'bar',data:{labels:entries.map(x=>x.k),datasets:[{label:'Taxa de abstenção',data:entries.map(x=>x.rate),backgroundColor:'#2563eb',borderRadius:7,categoryPercentage:.62,barPercentage:.68}]},options:{...base(),indexAxis:'y',layout:{padding:{right:54}},scales:{x:{beginAtZero:true,max:Math.max(50,Math.ceil(Math.max(...entries.map(x=>x.rate),1)/10)*10),ticks:{callback:v=>`${fmt(v)}%`},grid:{color:'#eef2f7'}},y:{grid:{display:false},ticks:{autoSkip:false}}},plugins:{...base().plugins,legend:{display:false},tooltip:{callbacks:{label:c=>` ${pct(c.raw)}`}}}}})}
function drawHeat(a){const ages=vals(a,F.idade).sort((x,y)=>ageStart(x)-ageStart(y)),gs=vals(a,F.genero);const m={};a.forEach(r=>{const k=`${r[F.idade]}|${r[F.genero]}`;m[k]??={c:0,a:0};m[k].c+=n(r[F.comp]);m[k].a+=n(r[F.abs])});let max=0;Object.values(m).forEach(v=>{v.r=(v.c+v.a)?100*v.a/(v.c+v.a):0;max=Math.max(max,v.r)});document.getElementById('ta3-heat').innerHTML=`<div class="ta3-heat-wrap"><table class="ta3-heat"><thead><tr><th>Faixa etária</th>${gs.map(g=>`<th>${esc(g)}</th>`).join('')}</tr></thead><tbody>${ages.map(age=>`<tr><th>${esc(age)}</th>${gs.map(g=>{const v=m[`${age}|${g}`]||{r:0,a:0};const al=max ? (.12 + .78*v.r/max) : .12;return `<td style="background:rgba(37,99,235,${al.toFixed(2)})"><strong>${pct(v.r)}</strong><small>${fmt(v.a)} aus.</small></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
function drawFac(a){destroy('fac');const calc=pred=>{const z=a.filter(pred),fac=sum(z,F.fac),cc=sum(z,F.compFac);return fac?100*cc/fac:0};const young=calc(r=>{const s=ageStart(r[F.idade]);return s===16||s===17}),old=calc(r=>ageStart(r[F.idade])>=70);charts.fac=new Chart(document.getElementById('ta3-fac'),{type:'bar',data:{labels:['16–17 anos','70 anos ou mais'],datasets:[{label:'Taxa de comparecimento',data:[young,old],backgroundColor:['#06b6d4','#8b5cf6'],borderRadius:8,categoryPercentage:.58,barPercentage:.62}]},options:{...base(),layout:{padding:{top:24}},scales:{y:{beginAtZero:true,max:100,ticks:{callback:v=>`${fmt(v)}%`},grid:{color:'#eef2f7'}},x:{grid:{display:false}}},plugins:{...base().plugins,legend:{display:false},tooltip:{callbacks:{label:c=>` ${pct(c.raw)}`}}}}})}
function drawPcd(a){destroy('pcd');const apt=sum(a,F.aptos),abs=sum(a,F.abs),pc=sum(a,F.pcdComp),pa=sum(a,F.pcdAbs);const general=apt?100*abs/apt:0,pcd=(pc+pa)?100*pa/(pc+pa):0;charts.pcd=new Chart(document.getElementById('ta3-pcd'),{type:'bar',data:{labels:['Geral','Eleitorado PCD'],datasets:[{label:'Taxa de abstenção',data:[general,pcd],backgroundColor:['#94a3b8','#f59e0b'],borderRadius:8,categoryPercentage:.58,barPercentage:.62}]},options:{...base(),layout:{padding:{top:24}},scales:{y:{beginAtZero:true,max:Math.max(40,Math.ceil(Math.max(general,pcd)/10)*10),ticks:{callback:v=>`${fmt(v)}%`},grid:{color:'#eef2f7'}},x:{grid:{display:false}}},plugins:{...base().plugins,legend:{display:false},tooltip:{callbacks:{label:c=>` ${pct(c.raw)}`}}}}})}
function drawAge(a){destroy('age');const entries=Object.entries(group(a,F.idade)).sort((x,y)=>ageStart(x[0])-ageStart(y[0]));charts.age=new Chart(document.getElementById('ta3-age'),{type:'bar',data:{labels:entries.map(x=>x[0]),datasets:[{label:'Comparecimento',data:entries.map(x=>x[1].comp),backgroundColor:'#2563eb',borderRadius:6,categoryPercentage:.62,barPercentage:.66},{label:'Abstenção',data:entries.map(x=>x[1].abs),backgroundColor:'#f59e0b',borderRadius:6,categoryPercentage:.62,barPercentage:.66}]},options:{...base(),layout:{padding:{top:26}},scales:{x:{grid:{display:false},ticks:{maxRotation:35}},y:{beginAtZero:true,grid:{color:'#eef2f7'},ticks:{callback:v=>fmt(v)}}}}})}
function init(){css();ensureNav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();